'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..');
const load=()=>import('../atlas-utils.mjs');
const note={id:'a',source_kind:'notion-curated',title:'자아의 기억',body:'G2.21 준비',concept:'자아',provenance:'ACTIVE DERIVATIVE'};
const paper={id:'b',source_kind:'notion-curated-paper-note',title:'A Truth Maintenance System',body:'비교 자료',concept:'',provenance:'ACTIVE DERIVATIVE',bibliography:{author:'Doyle',year:1979,read_status:'가정·정당화 일부 검토',original_claim:'수정 가능한 정당화 구조',limitations:'전체 검증 아님'}};
test('search includes existing titles and content',async()=>{const {filterResearchRecords}=await load();assert.deepEqual(filterResearchRecords([note,paper],{query:'G2.21'}).map(x=>x.id),['a']);});
test('search reaches bibliographic author',async()=>{const {filterResearchRecords}=await load();assert.deepEqual(filterResearchRecords([note,paper],{query:'doyle'}).map(x=>x.id),['b']);});
test('search reaches read-depth and caveat',async()=>{const {filterResearchRecords}=await load();assert.equal(filterResearchRecords([note,paper],{query:'전체 검증 아님'}).length,1);});
test('source categories remain distinct',async()=>{const {filterResearchRecords}=await load();assert.deepEqual(filterResearchRecords([note,paper],{kind:'paper'}).map(x=>x.id),['b']);assert.deepEqual(filterResearchRecords([note,paper],{kind:'theory'}).map(x=>x.id),['a']);});
test('search does not mutate source records',async()=>{const {filterResearchRecords}=await load();const records=[paper,note];filterResearchRecords(records,{query:'G2.21'});assert.strictEqual(records[0],paper);});
test('paper depth is explicit and does not become an original',async()=>{const {readingDepth}=await load();assert.equal(readingDepth(note),null);const depth=readingDepth(paper);assert.equal(depth.scope,'가정·정당화 일부 검토');assert.match(depth.origin,/논문 원문이 아님/);});
test('unread paper has visible epistemic hold',async()=>{const {readingDepth}=await load();const depth=readingDepth({...paper,bibliography:{}});assert.match(depth.scope,/미기록/);assert.match(depth.limit,/확인 필요/);});
test('topic trails are unique and meaningful',async()=>{const {RESEARCH_TRAILS}=await load();assert.equal(new Set(RESEARCH_TRAILS.map(x=>x.id)).size,RESEARCH_TRAILS.length);assert.ok(RESEARCH_TRAILS.some(x=>x.query==='G2.21'));});
test('browser page and workspace use shared source-atlas module',()=>{const html=fs.readFileSync(path.join(root,'index.html'),'utf8'),js=fs.readFileSync(path.join(root,'workspace.js'),'utf8');assert.match(html,/id="record-reading-guide"/);assert.match(html,/id="reading-trails"/);assert.match(js,/from '\.\/atlas-utils\.mjs'/);assert.match(js,/readingDepth\(r\)/);});
test('public source custody manifest remains at established scope',()=>{const manifest=JSON.parse(fs.readFileSync(path.join(root,'content/public/records.json'),'utf8'));assert.equal(manifest.records.length,21);assert.equal(manifest.records.filter(r=>r.id==='g222-p1-rival-semantics').length,1);assert.ok(manifest.records.every(x=>x.provenance==='ACTIVE DERIVATIVE'));assert.ok(manifest.records.every(x=>!x.includes_pdf_bytes));assert.ok(manifest.records.every(x=>!x.id.startsWith('new-hacking-')&&!x.id.startsWith('new-kreisel-')));});
