'use strict';
// G2.24-P1: finite researcher-designed negative controls, NOT participant-data inference.
const assert=require('node:assert/strict');
const BIT=[0,1];
function assertBit(x){if(!BIT.includes(x))throw new RangeError('binary host only');return x;}
function observe(u){assertBit(u);return Object.freeze({u,a0:u,b0:u,a1:u,b1:u});}
// Lagged transition means there is NO instantaneous feedback cycle.
function twoAgent(model,u,{a0=u,b0=u}={}){
 assertBit(u);assertBit(a0);assertBit(b0);
 if(!['common','forward','reciprocal'].includes(model))throw new RangeError('unknown model');
 const a1=model==='reciprocal'?b0:u;
 const b1=model==='common'?u:a0;
 return {a1,b1};
}
function modelSurvivors(observations){
 if(!Array.isArray(observations))throw new TypeError('records');
 return ['common','forward','reciprocal'].filter(model=>observations.every(({u,a0,b0,a1,b1})=>{
   const r=twoAgent(model,u,{a0,b0});return r.a1===a1&&r.b1===b1;
 }));
}
function preregisteredCourt(){
 const natural=BIT.map(u=>observe(u));
 const forwardTest={u:0,a0:1,b0:0,a1:0,b1:1};
 const reverseTest={u:0,a0:0,b0:1,a1:1,b1:0};
 return {natural,forwardTest,reverseTest,
  naturalSurvivors:modelSurvivors(natural),
  afterForward:modelSurvivors([...natural,forwardTest]),
  afterBoth:modelSurvivors([...natural,forwardTest,reverseTest]),
  status:'SYNTHETIC_INTERVENTION_ASSUMED_NOT_PERFORMED_ON_PEOPLE'};
}
// Binary potential-outcome completions given U~Bern(1/2), X=U, Y=X naturally.
// Observed Y(0) for U=0 and Y(1) for U=1. Other two are unknown.
function completions(){
 const options=[];
 for(const y1IfU0 of BIT)for(const y0IfU1 of BIT){
   const y0u0=0,y1u1=1;
   const ate=(y1IfU0-y0u0+y1u1-y0IfU1)/2;
   options.push({y1IfU0,y0IfU1,ate});
 }
 return options;
}
function sharpBounds(){
 const rows=completions();
 return {lower:Math.min(...rows.map(x=>x.ate)),upper:Math.max(...rows.map(x=>x.ate)),
  values:[...new Set(rows.map(x=>x.ate))].sort((a,b)=>a-b),witnesses:rows,
  assumptions:['binary outcome','consistency','equal U strata','observed X=U,Y=U','no added cross-world restrictions']};
}
function positivityAudit(){
 return BIT.map(u=>({stratum:u,supportedTreatment:[u],missingTreatment:[1-u]}));
}
// Same public signals can be generated by incompatible mental-state assignments.
function recognitionWorlds(publicSignals={aAcknowledges:1,bAcknowledges:1}){
 const a=assertBit(publicSignals.aAcknowledges),b=assertBit(publicSignals.bAcknowledges);
 return BIT.map(bInternallyRecognizes=>({
   aAcknowledges:a,bAcknowledges:b,bInternallyRecognizes,
   publiclyIndistinguishable:true,
 }));
}
function adjudicateRecognition(publicSignals){
 const worlds=recognitionWorlds(publicSignals);
 return {mutualPublicAcknowledgment:worlds.every(w=>w.aAcknowledges===1&&w.bAcknowledges===1),
  internalRecognitionEntailed:worlds.every(w=>w.bInternallyRecognizes===1),
  indistinguishableInternalStates:new Set(worlds.map(w=>w.bInternallyRecognizes)).size,
  humanKnowledge:'NOT_ADJUDICATED'};
}
function report(){
 return {court:preregisteredCourt(),bounds:sharpBounds(),positivity:positivityAudit(),
 recognition:adjudicateRecognition({aAcknowledges:1,bAcknowledges:1}),
 status:'G224_P1_FINITE_REFERENCE_ONLY; AUTHOR_FIDELITY_HOLD; G221_B0_B6_NO_RUN'};
}
module.exports={observe,twoAgent,modelSurvivors,preregisteredCourt,completions,sharpBounds,positivityAudit,recognitionWorlds,adjudicateRecognition,report};
